"""Puertos de persistencia: la capa de aplicación y la API dependen de estas
interfaces, nunca de SQLAlchemy (ADR 0004)."""

from datetime import datetime
from typing import Protocol

from noc.domain.nodes.entities import GatewayInfo, Node, NodeSummary, Position, Telemetry


class NodeRepository(Protocol):
    async def upsert_from_sighting(self, node: Node, seen_at: datetime) -> Node: ...
    async def touch_last_seen(self, node_id: str, gateway_id: str | None, seen_at: datetime) -> None: ...
    async def get(self, node_id: str) -> Node | None: ...
    async def list_summaries(self) -> list[NodeSummary]: ...


class PositionRepository(Protocol):
    async def add(self, position: Position) -> None: ...
    async def list_for_node(self, node_id: str, limit: int) -> list[Position]: ...


class TelemetryRepository(Protocol):
    async def add(self, telemetry: Telemetry) -> None: ...
    async def list_for_node(self, node_id: str, limit: int, kind: str | None) -> list[Telemetry]: ...


class GatewayRepository(Protocol):
    async def upsert(self, info: GatewayInfo) -> None: ...
    async def list_all(self) -> list[GatewayInfo]: ...
